AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Telegram sender

Globals:
  Function:
    Timeout: 5

Resources:
  TelegramMessageQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 10
  TelegramMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: 'telegram-ids/*'
      Events:
        TelegramMessageReceivedSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt TelegramMessageQueue.Arn
            BatchSize: 1

Outputs:
  TelegramMessageQueueArn:
    Description: Telegram message queue Arn
    Value: !GetAtt TelegramMessageQueue.Arn
    Export:
      Name: TelegramMessageQueueArn