AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Telegram sender

Globals:
  Function:
    Timeout: 5
    MemorySize: 512

Resources:
  TelegramMessageQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 10
  TelegramMessageFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: ./rust_app
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: 'telegram-ids/*'
      Events:
        TelegramMessageReceivedSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt TelegramMessageQueue.Arn
            BatchSize: 1

Outputs:
  TelegramMessageQueueUrl:
    Description: Telegram message queue Url
    Value: !Ref TelegramMessageQueue
    Export:
      Name: TelegramMessageQueueUrl
  TelegramMessageQueueName:
    Description: Telegram message queue name
    Value: !GetAtt TelegramMessageQueue.QueueName
    Export:
      Name: TelegramMessageQueueName